export const FIND_VIDEO_BY_ID_REQUEST = 'FIND_VIDEO_BY_ID_REQUEST' 
export const FIND_VIDEO_BY_ID_SUCESS = 'FIND_VIDEO_BY_ID_SUCESS' 
export const FIND_VIDEO_BY_ID_FAILURE = 'FIND_VIDEO_BY_ID_FAILURE' 

export const FIND_VIDEO_REQUEST = 'FIND_VIDEO_REQUEST' 
export const FIND_VIDEO_SUCESS = 'FIND_VIDEO_SUCESS' 
export const FIND_VIDEO_FAILURE = 'FIND_VIDEO_FAILURE' 


export const EDIT_VIDEO_REQUEST = 'EDIT_VIDEO_REQUEST'
export const EDIT_VIDEO_SUCCESS = 'EDIT_VIDEO_SUCCESS'
export const EDIT_VIDEO_FAILURE = 'EDIT_VIDEO_FAILURE'

export const CREATE_VIDEO_REQUEST = 'CREATE_VIDEO_REQUEST'
export const CREATE_VIDEO_SUCCESS = 'CREATE_VIDEO_SUCCESS'
export const CREATE_VIDEO_FAILURE = 'CREATE_VIDEO_FAILURE'

export const DELETE_VIDEO_REQUEST = 'DELETE_VIDEO_REQUEST'
export const DELETE_VIDEO_SUCCESS = 'DELETE_VIDEO_SUCCESS'
export const DELETE_VIDEO_FAILURE = 'DELETE_VIDEO_FAILURE'